version: '3.2'

services:
  eureka:
    image: "microservice/eureka-server:${project_version:?err}"
    container_name: microservice-eureka-server
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${profile}
    volumes:
      - type: bind
        source: ${log_dir}/logs
        target: /logs
  oauth2:
    image: "microservice/oauth2-server:${project_version:?err}"
    container_name: microservice-oauth2-server
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${profile}
    volumes:
      - type: bind
        source: ${log_dir}/logs
        target: /logs
  geteway: 
    image: "microservice/apigateway:${project_version:?err}"
    container_name: microservice-apigateway-server
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: ${profile}
    volumes:
      - type: bind
        source: ${log_dir}/logs
        target: /logs
    ports: 
      - "80:80"
      - "443:443"
