spring:
  application:
    name: micorservice-api-gateway
server:
  port: 9000
  
zuul:
  trace-request-body: true
  routes:
    register:
      service-id: microservice-eureka-server
      id: eureka.server
      path: /eureka/**
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie

  
  
eureka:
  client:
    service-url:
      defaultZone: http://admin:secret@localhost:9081/eureka/
