spring:
  application:
    name: microservice-social-cloud
  resources:
    static-locations:
    - file:logs
    - classpath:static
    
  mvc:
    static-path-pattern: /**
server:
    servlet:
      session: 
        persistent: true
security:
  oauth2:
    client:
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-id: 0f95689942edeb1555cd
      client-secret: 52158230421cd91abbea3b7b29fb355d2d006fb0
      authentication-scheme: query
      token-name: access_token
      client-authentication-scheme: query
    resource:
      user-info-uri: https://api.github.com/user
logging:
  level:
    root: INFO
    org.springframework.security: info
  
      
          